const mongoose=require('mongoose');
const postSchema= mongoose.Schema({
    title:{
        type:String,
        required:true
    },
    user_id:{
        type:String,
        required:true
    },
    date:{
        type:String,
    },
    time:{
        type:String
    },
    blog_tag:{
        // Extra added 
        type:String,
        required:true
    },
    content:{
        type:String,
        required:true
    },
    image:{
        type:String,
        default:''
    },
    views:{
        type:Number,
        default:0
    },
    comments:{
        type:Object,
        default:{}
    }
});
module.exports=mongoose.model('Post',postSchema);